### ISSUE TITLE
Resource reload failed

### ISSUE THREAD

**Issue by Gulli03** [Valdr687/Vervada-s-enhanced-plants#1]
After adding the continuity mod to my game, it says resource reload failed every time I try to add this resource-pack.
Any Idea what could cause this and possible fixes?

**Comment by Gulli03** [comment]
nvm, forgor to install indium, im just stupid

**Comment by Valdr687** [comment]
In the future you might want to use [Fabulously Optimized](https://modrinth.com/modpack/fabulously-optimized) to avoid that kind of issues.
Can't deny there's a bias as I'm a contributor of the project but you wan't have missing dependencies that way - and I'm building my pack for it.
Anyways, glad you have resolved your issue.

**Comment by Gulli03** [comment]
No thanks, I dont use modpacks like these. I'd rather go out of my way to download the mods I need myself. I'm just used to Mods complaining about dependencies on startup. But I guess continuity doesn't do that

**Comment by Valdr687** [comment]
And you're not the only one who noticed it, it's now on their [radar](https://github.com/PepperCode1/Continuity/issues/415). Hopefully it will be fixed at some point.
